name: Generate and Deploy GitHub Activity Summary

on:
  schedule:
    - cron: "0 0 * * 0" # Runs weekly on Sunday at midnight
  workflow_dispatch:

jobs:
  summarize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai requests

      - name: Run summary generator
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python main.py > activity_summary.md

      - name: Checkout GitHub Pages repository
        uses: actions/checkout@v4
        with:
          repository: Rvndyr/rvndyr.github.io
          path: gh-pages
          token: ${{ secrets.GH_PAT }}

      - name: Copy summary file
        run: |
          mkdir -p gh-pages/public/timeline
          cp activity_summary.md gh-pages/public/timeline/

      - name: Commit and push changes
        working-directory: gh-pages
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add src/timeline/activity_summary.md
          git commit -m "Update GitHub activity summary [skip ci]" || echo "No changes to commit"
          git push
